language: java
jdk: oraclejdk6

install:
- ./gradlew install --info

script:
- ./gradlew check
- ./gradlew -p acceptance-test test

after_success:
- test ${TRAVIS_TAG} -a ${BINTRAY} && ./gradlew -Pversion=${TRAVIS_TAG#v} bintrayUpload

env:
  global:
  - TERM=dumb
